---
title: "Eda of Imputed CMI data."
author: Paschalis Dompoudis
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
affiliation: Simtec Software and Services
abstract: This R file performs Exploratory Data Analysis on the initial dataset that
  contains **only** the tabular data available from the CMI competition.
  The final imputed dataset that was used for training can be found in the *data* folder.
  The **Isolation Forest** method was used to isolate and remove outliers from the dataset. An **Iterative           Imputer** with the **Extra Tree Regressor** as an estimator was used to fill empty numerical features. 
  For categorical features a **Simple Imputer** was used replacing the NA values 
  with the most frequent value of the feature. Finally the dataset is also standardized
  to have 0 mean and 1 standard deviation.
params:
  data_csv: "D:/CMI-PIU/data/train.csv"
df_print: paged
---

```{r, packages, include=FALSE}
library(dplyr)
library(ggplot2)
```

# Summary

```{r, initial}
data <- read.csv(params$data_csv)

n_rows <- nrow(data)
n_cols <- ncol(data)

is_discrete <- sapply(data, function(col) is.factor(col) || is.character(col))
is_numeric <- sapply(data, is.numeric)

n_discrete <- sum(is_discrete)
n_numeric <- sum(is_numeric)

n_missing <- sum(is.na(data))

# Get columns where the number of NA values is equal to the number of the rows
n_all_missing_columns <- sum(colSums(is.na(data)) == n_rows)
n_complete_rows <- sum(complete.cases(data))
total_observations <- n_rows * n_cols

summary_table <- data.frame(
  Metric = c("Number of Rows", "Number of Columns", "Number of Discrete Features",
             "Number of Numeric Features", "Number of Missing DPs", "All Missing Columns",
             "Complete Rows", "Total Observations"),
  Value = c(n_rows, n_cols, n_discrete, n_numeric, n_missing, n_all_missing_columns,
            n_complete_rows, total_observations)
)

summary_table



```

# Missing Data

```{r, missing_data}
# Create empty list
m <- c()

# Loop through each column and count missing values
for(i in colnames(data)){
  n_missing <- sum(is.na(data[,i]))
  missing_percentage <- n_missing / n_rows
  m <- append(m, missing_percentage)
}

# Convert m to table in order to plot a bar chart
m_table <- data.frame(
  Names = c(colnames(data)),
  Missing = m
)

# Reorder the Names factor based on Missing values
m_table$Names <- factor(m_table$Names, levels = m_table$Names[order(m_table$Missing)])

# Plot a bar chart with ggplot
ggplot(m_table, aes(x = Names, y = Missing)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x = "Column Names", y = "Missing Percentage", title = "Missing Data Percentage by Column")

```
